    location = /games { return 301 /games/; }
    location ^~ /games/ {
        proxy_pass http://127.0.0.1:4399/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 90s;
        proxy_send_timeout 90s;
        client_max_body_size 16k;
    }
